version: '3'

services: 
    mongo:
        image: mongo
        container_name: mongo-service
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=test
            - MONGO_INITDB_ROOT_PASSWORD=test
        ports: 
            - 27019:27017
        expose: 
            - 27019
    
    back:
        container_name: "heroes-service"
        restart: always
        environment: 
            - COLLECTION_MONGO=arbol_rubro
            - DB_MONGO=test
            - USER_MONGO=test
            - PASS_MONGO=test
            - HOST_MONGO=mongo
            - PORT_MONGO=27019
        build: .
        ports: 
            - 3000:3000
        volumes: 
            - .:/usr/src/app
        depends_on: 
            - mongo
        links: 
            - mongo